import type {
  AgentProviderCapabilitiesDto,
  AgentRuntimeStatusDto,
  ThreadDetailDto,
  ThreadDto,
} from '@pockymoe/shared';

const now = new Date('2026-06-08T14:20:00.000Z').toISOString();

export const mockThreads: ThreadDto[] = [
  {
    id: 'thread-safety-review',
    workspaceId: 'workspace-chemistry',
    provider: 'codex',
    providerSessionId: 'codex-session-001',
    source: 'supervisor',
    title: 'Safety review for Grignard setup',
    model: 'gpt-5.4',
    reasoningEffort: 'medium',
    fastMode: false,
    collaborationMode: 'default',
    approvalMode: 'guarded',
    sandboxMode: 'workspace-write',
    status: 'running',
    summaryText:
      'Assessing hazards and instrument setup for a wet-lab workflow.',
    lastError: null,
    activeTurnId: 'turn-2',
    isLoaded: true,
    isPinned: true,
    createdAt: '2026-06-08T13:45:00.000Z',
    updatedAt: now,
    lastTurnStartedAt: '2026-06-08T14:17:00.000Z',
    lastTurnCompletedAt: null,
    contextUsage: {
      availability: 'available',
      remainingPercent: 72,
      tokensInContextWindow: 44800,
      modelContextWindow: 128000,
      updatedAt: now,
    },
  },
  {
    id: 'thread-molecule-viewer',
    workspaceId: 'workspace-chemistry',
    provider: 'codex',
    providerSessionId: 'codex-session-002',
    source: 'supervisor',
    title: 'Render solvent molecule',
    model: 'gpt-5.4',
    reasoningEffort: 'medium',
    fastMode: false,
    collaborationMode: 'default',
    approvalMode: 'guarded',
    sandboxMode: 'workspace-write',
    status: 'idle',
    summaryText: 'XYZ artifact rendering smoke thread.',
    lastError: null,
    activeTurnId: null,
    isLoaded: true,
    isPinned: false,
    createdAt: '2026-06-08T12:10:00.000Z',
    updatedAt: '2026-06-08T12:35:00.000Z',
    lastTurnStartedAt: '2026-06-08T12:30:00.000Z',
    lastTurnCompletedAt: '2026-06-08T12:35:00.000Z',
  },
];

export const mockDetail: ThreadDetailDto = {
  thread: mockThreads[0],
  workspace: {
    id: 'workspace-chemistry',
    hostId: 'local',
    label: 'Computational Chemistry',
    absPath: '/workspace/computational-chemistry',
    isFavorite: true,
    createdAt: '2026-06-07T10:00:00.000Z',
    lastOpenedAt: now,
  },
  workspacePathStatus: 'present',
  totalTurnCount: 2,
  pendingRequests: [],
  pendingSteers: [],
  turns: [
    {
      id: 'turn-1',
      startedAt: '2026-06-08T14:10:00.000Z',
      status: 'completed',
      error: null,
      model: 'gpt-5.4',
      reasoningEffort: 'medium',
      reasoningEffortAvailable: true,
      tokenUsage: {
        total: {
          totalTokens: 3180,
          inputTokens: 2300,
          cachedInputTokens: 400,
          outputTokens: 680,
          reasoningOutputTokens: 200,
        },
        last: {
          totalTokens: 3180,
          inputTokens: 2300,
          cachedInputTokens: 400,
          outputTokens: 680,
          reasoningOutputTokens: 200,
        },
        modelContextWindow: 128000,
      },
      priceEstimate: null,
      items: [
        {
          id: 'item-user-1',
          kind: 'userMessage',
          text: 'Review this Grignard setup before I start the run.\nKeep the answer compact and call out the highest-risk step first.',
          transcriptOrder: 1,
          sourceTurnId: 'turn-1',
          createdAt: '2026-06-08T14:10:03.000Z',
        },
        {
          id: 'item-reasoning-1',
          kind: 'reasoning',
          text: 'I will separate chemical, physical, and operational risks, then propose controls that are actionable in the lab.',
          previewText: 'Risk categories and control plan.',
          transcriptOrder: 2,
          sourceTurnId: 'turn-1',
          createdAt: '2026-06-08T14:10:09.000Z',
        },
        {
          id: 'item-command-1',
          kind: 'commandExecution',
          text: 'rg -n "ether|quench|ignition" protocols/grignard-safety.md',
          previewText:
            'rg -n "ether|quench|ignition" protocols/grignard-safety.md',
          status: 'completed',
          transcriptOrder: 3,
          sourceTurnId: 'turn-1',
          createdAt: '2026-06-08T14:10:18.000Z',
        },
        {
          id: 'item-tool-1',
          kind: 'toolCall',
          text: 'farmaco.search_safety_context({ "query": "Grignard ether quench hazards" })',
          previewText: 'Queried Farmaco safety context.',
          status: 'completed',
          transcriptOrder: 4,
          sourceTurnId: 'turn-1',
          createdAt: '2026-06-08T14:10:25.000Z',
        },
        {
          id: 'item-file-read-1',
          kind: 'fileRead',
          text: 'Read workspace file protocols/grignard-safety.md',
          previewText: 'protocols/grignard-safety.md',
          detailText:
            '# Grignard setup\n\n- Verify dry glassware\n- Keep condenser water flowing\n- Stage quench behind a blast shield\n',
          transcriptOrder: 5,
          sourceTurnId: 'turn-1',
          createdAt: '2026-06-08T14:10:31.000Z',
        },
        {
          id: 'item-file-change-1',
          kind: 'fileChange',
          text: 'Updated reports/safety-review.md with the hazard checklist.',
          previewText: 'reports/safety-review.md',
          detailText:
            'Added ignition, exotherm, moisture ingress, and quench staging controls.',
          changedFiles: 1,
          addedLines: 8,
          removedLines: 0,
          transcriptOrder: 6,
          sourceTurnId: 'turn-1',
          createdAt: '2026-06-08T14:10:42.000Z',
        },
        {
          id: 'item-agent-1',
          kind: 'agentMessage',
          text: [
            'The main risks are ether vapor ignition, uncontrolled exotherm during initiation or quench, and moisture ingress causing pressure or runaway behavior.',
            '',
            '```tool-call',
            '{"tool":"farmaco.search_safety_context","args":{"query":"Grignard ether quench hazards"},"call_id":"safety-search-1"}',
            '```',
            '',
            '```tool-result',
            '{"call_id":"safety-search-1","result":{"status":"completed","result":"Found dry glassware, condenser flow, ignition control, and staged quench requirements.","stdout":"protocols/grignard-safety.md matched 4 controls\\n"}}',
            '```',
            '',
            'Before the run, verify dry glassware, inert gas continuity, condenser flow, blast shield position, and quench staging. Keep the initial iodine or dibromoethane activation step small and observable.',
            '',
            'A lightweight heat estimate is $q = mc\\Delta T$. For a staged addition:',
            '',
            '$$',
            '\\dot{q}_{release} < \\dot{q}_{cooling}',
            '$$',
          ].join('\n'),
          transcriptOrder: 7,
          sourceTurnId: 'turn-1',
          createdAt: '2026-06-08T14:11:13.000Z',
        },
      ],
    },
    {
      id: 'turn-2',
      startedAt: '2026-06-08T14:17:00.000Z',
      status: 'inProgress',
      error: null,
      model: 'gpt-5.4',
      reasoningEffort: 'medium',
      reasoningEffortAvailable: true,
      tokenUsage: null,
      priceEstimate: null,
      items: [
        {
          id: 'item-user-2',
          kind: 'userMessage',
          text: 'Show me a compact molecule artifact example too, so I can verify the workspace preview while redesigning this UI.',
          transcriptOrder: 7,
          sourceTurnId: 'turn-2',
          createdAt: '2026-06-08T14:17:04.000Z',
        },
        {
          id: 'item-command-2',
          kind: 'commandExecution',
          text: 'pnpm --filter @pockymoe/thread-ui test',
          previewText: 'pnpm --filter @pockymoe/thread-ui test',
          status: 'completed',
          transcriptOrder: 8,
          sourceTurnId: 'turn-2',
          createdAt: '2026-06-08T14:17:18.000Z',
        },
        {
          id: 'item-artifact-1',
          kind: 'artifact',
          text: 'Molecule artifact: ethanol geometry',
          previewText: 'Ethanol XYZ artifact',
          transcriptOrder: 9,
          sourceTurnId: 'turn-2',
          artifact: {
            id: 'artifact-ethanol',
            pluginId: 'remote-codex.workspace-molecule-preview',
            type: 'chemistry.molecule3d',
            title: 'Ethanol',
            summaryText: 'Small XYZ structure used for renderer smoke checks.',
            payload: {
              content: [
                [
                  '9',
                  'ethanol',
                  'C -0.748 0.015 0.024',
                  'C 0.748 -0.015 -0.024',
                  'O 1.382 1.184 0.212',
                  'H -1.104 0.557 0.875',
                  'H -1.144 0.544 -0.864',
                  'H -1.118 -1.005 0.047',
                  'H 1.111 -0.549 0.858',
                  'H 1.104 -0.576 -0.878',
                  'H 2.321 1.106 0.105',
                ].join('\n'),
              ],
              format: 'xyz',
              name: 'ethanol.xyz',
              uuid: 'artifact-ethanol',
            },
            assets: null,
            sourceTurnId: 'turn-2',
            sourceItemId: 'item-artifact-1',
            createdAt: now,
          },
        },
        {
          id: 'item-file-change-2',
          kind: 'fileChange',
          text: 'Created artifacts/ethanol.xyz for viewer testing.',
          previewText: 'artifacts/ethanol.xyz',
          detailText:
            '9\nethanol\nC -0.748 0.015 0.024\nC 0.748 -0.015 -0.024\nO 1.382 1.184 0.212\n',
          changedFiles: 1,
          addedLines: 11,
          removedLines: 0,
          transcriptOrder: 10,
          sourceTurnId: 'turn-2',
        },
      ],
    },
  ],
  liveItems: {
    turnId: 'turn-2',
    updatedAt: now,
    items: [
      {
        id: 'item-live-1',
        kind: 'agentMessage',
        text: 'I added a molecule artifact and will keep raw coordinate data in the artifact surface instead of letting it dominate the conversation.',
        transcriptOrder: 11,
        sourceTurnId: 'turn-2',
        createdAt: '2026-06-08T14:19:47.000Z',
      },
    ],
  },
  livePlan: {
    turnId: 'turn-2',
    explanation: 'Mock live plan for visual testing.',
    updatedAt: now,
    plan: [
      { step: 'Create compact artifact payload', status: 'completed' },
      { step: 'Verify plugin renderer surface', status: 'in_progress' },
      { step: 'Tighten chat layout hierarchy', status: 'pending' },
    ],
  },
};

export const mockStatus: AgentRuntimeStatusDto = {
  state: 'ready',
  transport: 'sdk',
  lastStartedAt: '2026-06-08T13:40:00.000Z',
  lastError: null,
  restartCount: 0,
};

export const mockCapabilities: AgentProviderCapabilitiesDto = {
  sessions: {
    list: true,
    read: true,
    resume: true,
    importLocal: true,
  },
  turns: {
    start: true,
    streamInput: true,
    steer: true,
    interrupt: true,
    compact: true,
  },
  branching: {
    fork: true,
    hardRollback: false,
    resumeAt: true,
    rewindFiles: false,
  },
  controls: {
    planMode: true,
    permissionRequests: true,
    sandboxMode: true,
    performanceMode: true,
    goals: true,
  },
  management: {
    models: true,
    mcpStatus: true,
    skills: true,
    hooks: true,
    hookTrust: true,
    hostConfigFiles: true,
    providerSettings: true,
  },
  usage: {
    contextWindow: true,
    tokenUsage: true,
    costUsd: true,
  },
};
